require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VacationsController do

  # This should return the minimal set of attributes required to create a valid
  # Vacation. As you add validations to Vacation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VacationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vacations as @vacations" do
      vacation = Vacation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vacations).should eq([vacation])
    end
  end

  describe "GET show" do
    it "assigns the requested vacation as @vacation" do
      vacation = Vacation.create! valid_attributes
      get :show, {:id => vacation.to_param}, valid_session
      assigns(:vacation).should eq(vacation)
    end
  end

  describe "GET new" do
    it "assigns a new vacation as @vacation" do
      get :new, {}, valid_session
      assigns(:vacation).should be_a_new(Vacation)
    end
  end

  describe "GET edit" do
    it "assigns the requested vacation as @vacation" do
      vacation = Vacation.create! valid_attributes
      get :edit, {:id => vacation.to_param}, valid_session
      assigns(:vacation).should eq(vacation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vacation" do
        expect {
          post :create, {:vacation => valid_attributes}, valid_session
        }.to change(Vacation, :count).by(1)
      end

      it "assigns a newly created vacation as @vacation" do
        post :create, {:vacation => valid_attributes}, valid_session
        assigns(:vacation).should be_a(Vacation)
        assigns(:vacation).should be_persisted
      end

      it "redirects to the created vacation" do
        post :create, {:vacation => valid_attributes}, valid_session
        response.should redirect_to(Vacation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vacation as @vacation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vacation.any_instance.stub(:save).and_return(false)
        post :create, {:vacation => {}}, valid_session
        assigns(:vacation).should be_a_new(Vacation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vacation.any_instance.stub(:save).and_return(false)
        post :create, {:vacation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vacation" do
        vacation = Vacation.create! valid_attributes
        # Assuming there are no other vacations in the database, this
        # specifies that the Vacation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vacation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vacation.to_param, :vacation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vacation as @vacation" do
        vacation = Vacation.create! valid_attributes
        put :update, {:id => vacation.to_param, :vacation => valid_attributes}, valid_session
        assigns(:vacation).should eq(vacation)
      end

      it "redirects to the vacation" do
        vacation = Vacation.create! valid_attributes
        put :update, {:id => vacation.to_param, :vacation => valid_attributes}, valid_session
        response.should redirect_to(vacation)
      end
    end

    describe "with invalid params" do
      it "assigns the vacation as @vacation" do
        vacation = Vacation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vacation.any_instance.stub(:save).and_return(false)
        put :update, {:id => vacation.to_param, :vacation => {}}, valid_session
        assigns(:vacation).should eq(vacation)
      end

      it "re-renders the 'edit' template" do
        vacation = Vacation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vacation.any_instance.stub(:save).and_return(false)
        put :update, {:id => vacation.to_param, :vacation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vacation" do
      vacation = Vacation.create! valid_attributes
      expect {
        delete :destroy, {:id => vacation.to_param}, valid_session
      }.to change(Vacation, :count).by(-1)
    end

    it "redirects to the vacations list" do
      vacation = Vacation.create! valid_attributes
      delete :destroy, {:id => vacation.to_param}, valid_session
      response.should redirect_to(vacations_url)
    end
  end

end
